# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeviceController.ui'
#
# Created: Wed Nov 17 10:34:47 2010
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(431, 270)
        Form.setMinimumSize(QtCore.QSize(455, 270))
        Form.setBaseSize(QtCore.QSize(415, 270))
        Form.setStyleSheet("""background-color: rgb(0, 0, 0);
alternate-background-color: rgb(0, 0, 0);""")
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(15, 40, 411, 191))
        self.tabWidget.setBaseSize(QtCore.QSize(24, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.targetSpin = QtGui.QDoubleSpinBox(self.tab_3)
        self.targetSpin.setGeometry(QtCore.QRect(10, 80, 111, 25))
        self.targetSpin.setObjectName("targetSpin")
        self.setTempCheck = QtGui.QCheckBox(self.tab_3)
        self.setTempCheck.setGeometry(QtCore.QRect(40, 10, 87, 21))
        self.setTempCheck.setObjectName("setTempCheck")
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.label.setObjectName("label")
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 30, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.sendCalBtn = QtGui.QPushButton(self.tab_3)
        self.sendCalBtn.setGeometry(QtCore.QRect(280, 80, 113, 32))
        self.sendCalBtn.setObjectName("sendCalBtn")
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 81, 20))
        self.label_2.setObjectName("label_2")
        self.maxTempSpin = QtGui.QDoubleSpinBox(self.tab_3)
        self.maxTempSpin.setGeometry(QtCore.QRect(140, 70, 100, 25))
        self.maxTempSpin.setDecimals(1)
        self.maxTempSpin.setMaximum(255.0)
        self.maxTempSpin.setProperty("value", QtCore.QVariant(50.0))
        self.maxTempSpin.setObjectName("maxTempSpin")
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(135, 35, 101, 25))
        self.label_5.setObjectName("label_5")
        self.delaySpin = QtGui.QDoubleSpinBox(self.tab_3)
        self.delaySpin.setGeometry(QtCore.QRect(140, 100, 100, 25))
        self.delaySpin.setDecimals(1)
        self.delaySpin.setMaximum(1000.0)
        self.delaySpin.setProperty("value", QtCore.QVariant(10.0))
        self.delaySpin.setObjectName("delaySpin")
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(109, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tempLabel = QtGui.QLabel(self.tab_3)
        self.tempLabel.setGeometry(QtCore.QRect(220, 10, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.tempLabel.setFont(font)
        self.tempLabel.setObjectName("tempLabel")
        self.heaterLevelLabel = QtGui.QLabel(self.tab_3)
        self.heaterLevelLabel.setGeometry(QtCore.QRect(249, 140, 100, 25))
        self.heaterLevelLabel.setObjectName("heaterLevelLabel")
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 100, 25))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.computerCheck = QtGui.QCheckBox(self.tab)
        self.computerCheck.setGeometry(QtCore.QRect(35, 130, 151, 21))
        self.computerCheck.setChecked(False)
        self.computerCheck.setObjectName("computerCheck")
        self.valveAllOff = QtGui.QPushButton(self.tab)
        self.valveAllOff.setGeometry(QtCore.QRect(230, 30, 113, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.valveAllOff.setPalette(palette)
        self.valveAllOff.setObjectName("valveAllOff")
        self.valveCleaning = QtGui.QPushButton(self.tab)
        self.valveCleaning.setGeometry(QtCore.QRect(230, 100, 113, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 255, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 255, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 127, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 170, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 174, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 255, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 255, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 127, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 170, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 127, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 255, 142))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 255, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 127, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 170, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 127, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 110, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 129, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.valveCleaning.setPalette(palette)
        self.valveCleaning.setObjectName("valveCleaning")
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(30, 10, 151, 116))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 101, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.valveSelect1 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.valveSelect1.setObjectName("valveSelect1")
        self.verticalLayout_2.addWidget(self.valveSelect1)
        self.valveSelect2 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.valveSelect2.setBaseSize(QtCore.QSize(50, 50))
        self.valveSelect2.setCursor(QtCore.Qt.PointingHandCursor)
        self.valveSelect2.setIconSize(QtCore.QSize(50, 50))
        self.valveSelect2.setObjectName("valveSelect2")
        self.verticalLayout_2.addWidget(self.valveSelect2)
        self.valveSelect3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.valveSelect3.setBaseSize(QtCore.QSize(50, 50))
        self.valveSelect3.setCursor(QtCore.Qt.PointingHandCursor)
        self.valveSelect3.setIconSize(QtCore.QSize(50, 50))
        self.valveSelect3.setObjectName("valveSelect3")
        self.verticalLayout_2.addWidget(self.valveSelect3)
        self.valveSelect4 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.valveSelect4.setBaseSize(QtCore.QSize(50, 50))
        self.valveSelect4.setCursor(QtCore.Qt.PointingHandCursor)
        self.valveSelect4.setIconSize(QtCore.QSize(50, 50))
        self.valveSelect4.setObjectName("valveSelect4")
        self.verticalLayout_2.addWidget(self.valveSelect4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pumpRunCheck = QtGui.QCheckBox(self.tab_2)
        self.pumpRunCheck.setGeometry(QtCore.QRect(50, 35, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pumpRunCheck.setFont(font)
        self.pumpRunCheck.setIconSize(QtCore.QSize(40, 40))
        self.pumpRunCheck.setObjectName("pumpRunCheck")
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(170, 35, 126, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pumpSpeedSpin = QtGui.QDoubleSpinBox(self.widget)
        self.pumpSpeedSpin.setObjectName("pumpSpeedSpin")
        self.horizontalLayout.addWidget(self.pumpSpeedSpin)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 401, 207))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ledRedLevel = QtGui.QDial(self.gridLayoutWidget)
        self.ledRedLevel.setNotchTarget(3.0)
        self.ledRedLevel.setNotchesVisible(True)
        self.ledRedLevel.setObjectName("ledRedLevel")
        self.gridLayout.addWidget(self.ledRedLevel, 3, 1, 1, 1)
        self.ledBlueLevel = QtGui.QDial(self.gridLayoutWidget)
        self.ledBlueLevel.setOrientation(QtCore.Qt.Horizontal)
        self.ledBlueLevel.setNotchTarget(3.0)
        self.ledBlueLevel.setNotchesVisible(True)
        self.ledBlueLevel.setObjectName("ledBlueLevel")
        self.gridLayout.addWidget(self.ledBlueLevel, 2, 1, 1, 1)
        self.ledGreenSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.ledGreenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ledGreenSlider.setObjectName("ledGreenSlider")
        self.gridLayout.addWidget(self.ledGreenSlider, 1, 2, 1, 1)
        self.ledBlueSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.ledBlueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ledBlueSlider.setObjectName("ledBlueSlider")
        self.gridLayout.addWidget(self.ledBlueSlider, 2, 2, 1, 1)
        self.ledRedSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.ledRedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ledRedSlider.setObjectName("ledRedSlider")
        self.gridLayout.addWidget(self.ledRedSlider, 3, 2, 1, 1)
        self.ledGreenSelect = QtGui.QRadioButton(self.gridLayoutWidget)
        self.ledGreenSelect.setObjectName("ledGreenSelect")
        self.gridLayout.addWidget(self.ledGreenSelect, 1, 0, 1, 1)
        self.ledBlueSelect = QtGui.QRadioButton(self.gridLayoutWidget)
        self.ledBlueSelect.setObjectName("ledBlueSelect")
        self.gridLayout.addWidget(self.ledBlueSelect, 2, 0, 1, 1)
        self.ledRedSelect = QtGui.QRadioButton(self.gridLayoutWidget)
        self.ledRedSelect.setObjectName("ledRedSelect")
        self.gridLayout.addWidget(self.ledRedSelect, 3, 0, 1, 1)
        self.ledGreenLevel = QtGui.QDial(self.gridLayoutWidget)
        self.ledGreenLevel.setNotchTarget(3.0)
        self.ledGreenLevel.setNotchesVisible(True)
        self.ledGreenLevel.setObjectName("ledGreenLevel")
        self.gridLayout.addWidget(self.ledGreenLevel, 1, 1, 1, 1)
        self.ledAllOff = QtGui.QRadioButton(self.gridLayoutWidget)
        self.ledAllOff.setObjectName("ledAllOff")
        self.gridLayout.addWidget(self.ledAllOff, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame = QtGui.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(100, 20, 211, 121))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 171, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rigLightsOff = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rigLightsOff.setObjectName("rigLightsOff")
        self.verticalLayout.addWidget(self.rigLightsOff)
        self.rigLightRed = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rigLightRed.setBaseSize(QtCore.QSize(50, 50))
        self.rigLightRed.setCursor(QtCore.Qt.PointingHandCursor)
        self.rigLightRed.setIconSize(QtCore.QSize(50, 50))
        self.rigLightRed.setObjectName("rigLightRed")
        self.verticalLayout.addWidget(self.rigLightRed)
        self.rigLightDimWhite = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rigLightDimWhite.setBaseSize(QtCore.QSize(50, 50))
        self.rigLightDimWhite.setCursor(QtCore.Qt.PointingHandCursor)
        self.rigLightDimWhite.setIconSize(QtCore.QSize(50, 50))
        self.rigLightDimWhite.setObjectName("rigLightDimWhite")
        self.verticalLayout.addWidget(self.rigLightDimWhite)
        self.rigLightBrightWhite = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.rigLightBrightWhite.setBaseSize(QtCore.QSize(50, 50))
        self.rigLightBrightWhite.setCursor(QtCore.Qt.PointingHandCursor)
        self.rigLightBrightWhite.setIconSize(QtCore.QSize(50, 50))
        self.rigLightBrightWhite.setObjectName("rigLightBrightWhite")
        self.verticalLayout.addWidget(self.rigLightBrightWhite)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.progressBar = QtGui.QProgressBar(self.tab_6)
        self.progressBar.setGeometry(QtCore.QRect(20, 20, 381, 23))
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.LambdaShutterCheckA = QtGui.QCheckBox(self.tab_7)
        self.LambdaShutterCheckA.setGeometry(QtCore.QRect(45, 50, 107, 21))
        self.LambdaShutterCheckA.setObjectName("LambdaShutterCheckA")
        self.LambdaFilterSpinA = QtGui.QComboBox(self.tab_7)
        self.LambdaFilterSpinA.setGeometry(QtCore.QRect(205, 90, 123, 26))
        self.LambdaFilterSpinA.setObjectName("LambdaFilterSpinA")
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.LambdaFilterSpinA.addItem(QtCore.QString())
        self.label_6 = QtGui.QLabel(self.tab_7)
        self.label_6.setGeometry(QtCore.QRect(50, 95, 134, 17))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_7, "")
        self.LambdaConnectedText = QtGui.QLabel(Form)
        self.LambdaConnectedText.setGeometry(QtCore.QRect(215, 240, 166, 17))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.LambdaConnectedText.setFont(font)
        self.LambdaConnectedText.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.LambdaConnectedText.setObjectName("LambdaConnectedText")
        self.ArduinoConnectedText = QtGui.QLabel(Form)
        self.ArduinoConnectedText.setGeometry(QtCore.QRect(25, 240, 166, 17))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.ArduinoConnectedText.setFont(font)
        self.ArduinoConnectedText.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.ArduinoConnectedText.setObjectName("ArduinoConnectedText")
        self.heaterLabel = QtGui.QLabel(Form)
        self.heaterLabel.setGeometry(QtCore.QRect(10, 5, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.heaterLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.heaterLabel.setFont(font)
        self.heaterLabel.setObjectName("heaterLabel")
        self.valveLabel = QtGui.QLabel(Form)
        self.valveLabel.setGeometry(QtCore.QRect(80, 10, 31, 17))
        self.valveLabel.setObjectName("valveLabel")
        self.LED_Indicator = QtGui.QLabel(Form)
        self.LED_Indicator.setGeometry(QtCore.QRect(190, 15, 26, 17))
        self.LED_Indicator.setAutoFillBackground(False)
        self.LED_Indicator.setStyleSheet("""border-color: rgb(0, 0, 0);
background-color: rgb(187, 38, 0);""")
        self.LED_Indicator.setObjectName("LED_Indicator")
        self.RigLight_Indicator = QtGui.QLabel(Form)
        self.RigLight_Indicator.setGeometry(QtCore.QRect(245, 15, 26, 17))
        self.RigLight_Indicator.setAutoFillBackground(False)
        self.RigLight_Indicator.setStyleSheet("""border-color: rgb(0, 0, 0);
background-color: rgb(187, 38, 0);""")
        self.RigLight_Indicator.setObjectName("RigLight_Indicator")
        self.Lambda_Indicator = QtGui.QLabel(Form)
        self.Lambda_Indicator.setGeometry(QtCore.QRect(370, 15, 26, 17))
        self.Lambda_Indicator.setAutoFillBackground(False)
        self.Lambda_Indicator.setStyleSheet("""border-color: rgb(0, 0, 0);
background-color: rgb(187, 38, 0);""")
        self.Lambda_Indicator.setObjectName("Lambda_Indicator")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.setTempCheck.setText(QtGui.QApplication.translate("Form", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Set Temp (deg C)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Calibrate", None, QtGui.QApplication.UnicodeUTF8))
        self.sendCalBtn.setText(QtGui.QApplication.translate("Form", "Store Cal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Last Cal:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxTempSpin.setSuffix(QtGui.QApplication.translate("Form", " C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Heater max:", None, QtGui.QApplication.UnicodeUTF8))
        self.delaySpin.setSuffix(QtGui.QApplication.translate("Form", " sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tempLabel.setText(QtGui.QApplication.translate("Form", "0.0 C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Heater level:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.computerCheck.setText(QtGui.QApplication.translate("Form", "Computer Control", None, QtGui.QApplication.UnicodeUTF8))
        self.valveAllOff.setText(QtGui.QApplication.translate("Form", "ALL OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.valveCleaning.setText(QtGui.QApplication.translate("Form", "Cleaning", None, QtGui.QApplication.UnicodeUTF8))
        self.valveSelect1.setText(QtGui.QApplication.translate("Form", "Valve 1", None, QtGui.QApplication.UnicodeUTF8))
        self.valveSelect2.setText(QtGui.QApplication.translate("Form", "Valve 2", None, QtGui.QApplication.UnicodeUTF8))
        self.valveSelect3.setText(QtGui.QApplication.translate("Form", "Valve 3", None, QtGui.QApplication.UnicodeUTF8))
        self.valveSelect4.setText(QtGui.QApplication.translate("Form", "Valve 4", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Valves", None, QtGui.QApplication.UnicodeUTF8))
        self.pumpRunCheck.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Pump", None, QtGui.QApplication.UnicodeUTF8))
        self.ledGreenSelect.setText(QtGui.QApplication.translate("Form", "Green 530nm", None, QtGui.QApplication.UnicodeUTF8))
        self.ledBlueSelect.setText(QtGui.QApplication.translate("Form", "Blue 470nm", None, QtGui.QApplication.UnicodeUTF8))
        self.ledRedSelect.setText(QtGui.QApplication.translate("Form", "Red 630nm", None, QtGui.QApplication.UnicodeUTF8))
        self.ledAllOff.setText(QtGui.QApplication.translate("Form", "ALL Off", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "LEDs", None, QtGui.QApplication.UnicodeUTF8))
        self.rigLightsOff.setText(QtGui.QApplication.translate("Form", "Lights OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.rigLightRed.setText(QtGui.QApplication.translate("Form", "Deep Red", None, QtGui.QApplication.UnicodeUTF8))
        self.rigLightDimWhite.setText(QtGui.QApplication.translate("Form", "Dim White", None, QtGui.QApplication.UnicodeUTF8))
        self.rigLightBrightWhite.setText(QtGui.QApplication.translate("Form", "Bright White", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Rig Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Form", "Timers", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaShutterCheckA.setText(QtGui.QApplication.translate("Form", "Shutter Open", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(0, QtGui.QApplication.translate("Form", "Blank (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(1, QtGui.QApplication.translate("Form", "340 nm (2)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(2, QtGui.QApplication.translate("Form", "350 nm (3)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(3, QtGui.QApplication.translate("Form", "380 nm (4)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(4, QtGui.QApplication.translate("Form", "Blank(5)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(5, QtGui.QApplication.translate("Form", "540 nm (6)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(6, QtGui.QApplication.translate("Form", "470 nm (7)", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaFilterSpinA.setItemText(7, QtGui.QApplication.translate("Form", "Open (8)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Wheel A Filter Setting", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("Form", "Lambda10-2", None, QtGui.QApplication.UnicodeUTF8))
        self.LambdaConnectedText.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cccccc;\">Lambda: Not Connected</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.ArduinoConnectedText.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cccccc;\">Lambda: Not Connected</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.heaterLabel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Rockwell Extra Bold\'; color:#ffffff;\">0.0 C</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.valveLabel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cecece;\">0</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LED_Indicator.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cccccc;\">Off</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.RigLight_Indicator.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cccccc;\">Off</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Lambda_Indicator.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cccccc;\">Off</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

